# Generated by Django 5.2.1 on 2025-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarywallet',
            name='status',
            field=models.CharField(choices=[('pending_generation', 'Ожидает генерации'), ('pending_deposit', 'Ожидает депозита'), ('deposit_detected', 'Депозит обнаружен'), ('sweep_initiated', 'Свип инициирован'), ('sweep_success', 'Свип успешен'), ('sweep_failed', 'Ошибка свипа'), ('expired', 'Просрочен'), ('error', 'Ошибка')], db_index=True, default='pending_generation', max_length=30),
        ),
    ]
