# Generated by Django 5.2.1 on 2025-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_optin',
            field=models.BooleanField(default=False),
        ),
    ]
