# Generated by Django 5.2.1 on 2025-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='functionality_limited_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
