# Generated by Django 5.2.1 on 2025-05-13 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGGED_IN', 'User Logged In'), ('USER_LOGGED_OUT', 'User Logged Out'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('EMAIL_VERIFIED', 'Email Verified'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('2FA_RESET_REQUESTED', '2FA Reset Requested'), ('2FA_RESET_COMPLETED', '2FA Reset Completed')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
