# Generated by Django 5.2.1 on 2025-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trusteddevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trusteddevice',
            options={'ordering': ['-last_login_at', '-added_at'], 'verbose_name_plural': 'Trusted Devices'},
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='device_identifier',
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='device_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='initial_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
