# Generated by Django 5.2.1 on 2025-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_trusteddevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
