# Generated by Django 5.2.1 on 2025-06-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name, e.g., 'Cross Arbitrage'", max_length=100, unique=True)),
                ('strategy_key', models.CharField(db_index=True, help_text="Unique key used in code, e.g., 'cross_arbitrage'", max_length=50, unique=True)),
                ('api_prefix', models.CharField(help_text="API URL prefix, e.g., '/api/investments/'", max_length=100, unique=True)),
                ('redis_channel', models.CharField(blank=True, help_text="Redis channel for payouts, e.g., 'payouts_cross_arbitrage'", max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this strategy is globally active')),
            ],
            options={
                'verbose_name': 'Investment Strategy',
                'verbose_name_plural': 'Investment Strategies',
            },
        ),
    ]
