# Generated by Django 5.2.1 on 2025-06-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_investmentstrategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trusteddevice',
            name='initial_fingerprint',
        ),
    ]
