# Generated by Django 5.2.1 on 2025-06-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cross Arbitrage, Flexible Arbitrage', max_length=100, unique=True)),
                ('strategy_key', models.CharField(db_index=True, help_text="Key used in code, e.g., 'cross_arbitrage'", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tool is active for accruals')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAccrual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source_profit_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referrals.investmenttool')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_referral_income', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='referrals_r_recipie_2ed38a_idx')],
            },
        ),
    ]
