# Generated by Django 5.2.1 on 2025-10-13 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_percent', models.DecimalField(decimal_places=4, default=0.07, help_text='Процент для рефералов 1-го уровня (7%)', max_digits=5)),
                ('level_2_percent', models.DecimalField(decimal_places=4, default=0.03, help_text='Процент для рефералов 2-го уровня (3%)', max_digits=5)),
                ('accrual_interval_hours', models.PositiveIntegerField(default=12, help_text='Интервал начислений в часах')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли реферальная программа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки реферальной программы',
                'verbose_name_plural': 'Настройки реферальной программы',
            },
        ),
        migrations.AddField(
            model_name='referralaccrual',
            name='source_model',
            field=models.CharField(default='unknown', help_text="Model name of the profit source (e.g., 'flexible_arbitrage.FlexiblePayout')", max_length=100),
        ),
        migrations.AddField(
            model_name='referralaccrual',
            name='source_object_id',
            field=models.CharField(default='0', help_text='ID of the specific profit record', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='referralaccrual',
            constraint=models.UniqueConstraint(fields=('recipient', 'level', 'investment_tool', 'source_model', 'source_object_id'), name='unique_referral_accrual'),
        ),
    ]
