# Generated by Django 5.2.1 on 2025-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarywallet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='temporarywallet',
            old_name='private_key_encrypted',
            new_name='encrypted_private_key',
        ),
        migrations.RemoveField(
            model_name='temporarywallet',
            name='used',
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='deposit_tx_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='detected_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='status',
            field=models.CharField(choices=[('pending_generation', 'Ожидает генерации'), ('pending_deposit', 'Ожидает депозита'), ('deposit_detected', 'Депозит обнаружен'), ('sweep_prep_pending', 'Подготовка к свипу (комиссия)'), ('sweep_prep_failed', 'Ошибка подготовки к свипу'), ('sweep_pending', 'Ожидание свипа'), ('sweep_success', 'Свип успешен'), ('sweep_failed', 'Ошибка свипа'), ('expired', 'Просрочен')], db_index=True, default='pending_generation', max_length=30),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='sweep_preparation_tx_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='sweep_tx_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='temporarywallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temporarywallet',
            name='address',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='temporarywallet',
            name='network',
            field=models.CharField(choices=[('TRC20', 'USDT - TRC20'), ('ARBITRUM', 'USDT - Arbitrum One'), ('BEP20', 'USDT - BNB Smart Chain (BEP20)')], db_index=True, max_length=20),
        ),
    ]
