# Generated by Django 5.2.1 on 2025-05-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_arbitrage', '0002_alter_temporarywallet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='target_wallet_network',
            field=models.CharField(blank=True, choices=[('TRC20', 'TRC20 (Tron)'), ('BEP20', 'BEP20 (BNB Smart Chain)'), ('ARBITRUM', 'Arbitrum')], max_length=50, null=True, verbose_name='Target Wallet Network'),
        ),
    ]
