# Generated by Django 5.2.1 on 2025-06-07 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_arbitrage', '0003_investmentaccount_target_wallet_network'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='network',
            field=models.CharField(choices=[('TRC20', 'TRC20 (Tron)'), ('BEP20', 'BEP20 (BNB Smart Chain)'), ('ARBITRUM', 'Arbitrum')], default='TRC20', max_length=50),
        ),
        migrations.AlterField(
            model_name='investmentaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts_cross_arbitrage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='investmentaccount',
            unique_together={('user', 'network')},
        ),
    ]
