# Generated by Django 5.2.1 on 2025-06-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_arbitrage', '0004_investmentaccount_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarywallet',
            name='status',
            field=models.CharField(choices=[('pending_generation', 'Ожидает генерации'), ('pending_deposit', 'Ожидает депозита'), ('deposit_detected', 'Депозит обнаружен'), ('sweep_key_requested', 'Ключ для свипа запрошен'), ('sweep_initiated', 'Свип инициирован'), ('sweep_prep_pending', 'Подготовка к свипу (комиссия)'), ('sweep_prep_failed', 'Ошибка подготовки к свипу'), ('sweep_pending', 'Ожидание свипа'), ('sweep_success', 'Свип успешен'), ('sweep_failed', 'Ошибка свипа'), ('expired', 'Просрочен')], db_index=True, default='pending_generation', max_length=30),
        ),
    ]
