# Generated by Django 5.2.1 on 2025-06-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_interval_minutes', models.IntegerField(default=15)),
                ('hot_pairs_limit', models.IntegerField(default=30)),
                ('coinglass_api_delay_ms', models.IntegerField(default=2100)),
                ('cmc_filters', models.JSONField(default=dict)),
                ('hot_pairs_criteria', models.JSONField(default=dict)),
                ('analytics_thresholds', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'SMC Configurations',
            },
        ),
        migrations.CreateModel(
            name='SMCSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('confidence', models.IntegerField()),
                ('patterns', models.JSONField()),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SMC Signals',
                'ordering': ['-created_at'],
            },
        ),
    ]
