# Generated by Django 5.2.1 on 2025-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCollectorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinglass_api_delay_ms', models.PositiveIntegerField(default=2100, help_text='Delay (in ms) between sequential CoinGlass API calls to avoid rate limits.')),
                ('cmc_filters', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Market Data Collector Configuration',
                'verbose_name_plural': 'Market Data Collector Configuration',
            },
        ),
        migrations.CreateModel(
            name='SmartMoneyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_interval_minutes', models.PositiveIntegerField(default=15, help_text='How often the analysis cycle runs (in minutes).')),
                ('hot_pairs_limit', models.PositiveIntegerField(default=30, help_text='Max number of hot pairs to analyze in detail.')),
                ('hot_pairs_criteria', models.JSONField(default=dict)),
                ('analytics_thresholds', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Smart Money Analyzer Configuration',
                'verbose_name_plural': 'Smart Money Analyzer Configuration',
            },
        ),
        migrations.DeleteModel(
            name='SMCConfiguration',
        ),
    ]
