# Generated by Django 5.2.1 on 2025-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc_settings', '0002_marketcollectorconfiguration_smartmoneyconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmcFilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=64)),
                ('min_volume_24h', models.DecimalField(decimal_places=2, default=30000000, max_digits=20)),
                ('min_market_cap', models.DecimalField(decimal_places=2, default=300000000, max_digits=20)),
                ('min_market_pairs', models.IntegerField(default=20)),
                ('min_age_days', models.IntegerField(default=90)),
                ('max_7d_change', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('min_rank', models.IntegerField(default=1)),
                ('max_rank', models.IntegerField(default=150)),
                ('min_exchanges', models.IntegerField(default=5)),
                ('blacklist', models.TextField(default='', help_text='Через запятую: safemoon,titan')),
                ('excluded_tags', models.TextField(default='', help_text='Через запятую: memes,casino,AI')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CoinMarketCap фильтр',
                'verbose_name_plural': 'CoinMarketCap фильтры',
            },
        ),
        migrations.DeleteModel(
            name='MarketCollectorConfiguration',
        ),
        migrations.DeleteModel(
            name='SmartMoneyConfiguration',
        ),
        migrations.DeleteModel(
            name='SMCSignal',
        ),
    ]
