# Generated by Django 5.2.1 on 2025-06-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc_settings', '0003_cmcfiltersettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMoneyStrategySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=64)),
                ('min_open_interest_usd', models.DecimalField(decimal_places=2, default=5000000, max_digits=20)),
                ('min_liquidations_usd', models.DecimalField(decimal_places=2, default=1000000, max_digits=20)),
                ('extreme_funding_threshold', models.DecimalField(decimal_places=4, default=0.01, max_digits=6)),
                ('liquidation_bias_ratio', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('taker_volume_ratio_threshold', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Настройки стратегии Smart Money',
                'verbose_name_plural': 'Настройки стратегий Smart Money',
            },
        ),
    ]
