# Generated by Django 5.2.1 on 2025-06-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smc_settings', '0004_smartmoneystrategysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmcfiltersettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cmcfiltersettings',
            name='min_exchanges',
        ),
    ]
