# Generated by Django 5.2.1 on 2025-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smc_settings', '0005_remove_cmcfiltersettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmoneystrategysettings',
            name='entry_deviation_percent',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Отклонение входа от текущей цены (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='smartmoneystrategysettings',
            name='sl_ratio',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Stop Loss (% от входа)', max_digits=5),
        ),
        migrations.AddField(
            model_name='smartmoneystrategysettings',
            name='tp_ratio',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Take Profit (% от входа)', max_digits=5),
        ),
    ]
