# Generated by Django 5.2.1 on 2025-06-07 01:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(default='defi_bot', help_text='Название стратегии (например, defi_bot)', max_length=64, unique=True)),
                ('payout_rate', models.DecimalField(decimal_places=5, default=Decimal('0.0012'), help_text='Процент в день (например, 0.0012 = 0.12%)', max_digits=6)),
                ('lock_days', models.IntegerField(default=30, help_text='Срок заморозки депозита (в днях)')),
                ('min_deposit', models.DecimalField(decimal_places=6, default=Decimal('100.000000'), help_text='Минимальный депозит для активации', max_digits=20)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли стратегия (если нет — выплаты не запускаются)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('TRC20', 'TRC20 (Tron)'), ('BEP20', 'BEP20 (BNB Smart Chain)'), ('ARBITRUM', 'Arbitrum')], default='TRC20', max_length=50)),
                ('balance', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('activated', models.BooleanField(default=False)),
                ('target_wallet', models.CharField(blank=True, max_length=128, null=True)),
                ('target_wallet_network', models.CharField(blank=True, choices=[('TRC20', 'TRC20 (Tron)'), ('BEP20', 'BEP20 (BNB Smart Chain)'), ('ARBITRUM', 'Arbitrum')], max_length=50, null=True, verbose_name='Target Wallet Network')),
                ('lock_days', models.IntegerField(default=30)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts_defi_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'network')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits_defi_bot', to='defi_bot.investmentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=128, unique=True)),
                ('encrypted_private_key', models.TextField()),
                ('network', models.CharField(choices=[('TRC20', 'USDT - TRC20'), ('ARBITRUM', 'USDT - Arbitrum One'), ('BEP20', 'USDT - BNB Smart Chain (BEP20)')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending_generation', 'Ожидает генерации'), ('pending_deposit', 'Ожидает депозита'), ('deposit_detected', 'Депозит обнаружен'), ('sweep_key_requested', 'Ключ для свипа запрошен'), ('sweep_initiated', 'Свип инициирован'), ('sweep_prep_pending', 'Подготовка к свипу (комиссия)'), ('sweep_prep_failed', 'Ошибка подготовки к свипу'), ('sweep_pending', 'Ожидание свипа'), ('sweep_success', 'Свип успешен'), ('sweep_failed', 'Ошибка свипа'), ('expired', 'Просрочен')], db_index=True, default='pending_generation', max_length=30)),
                ('deposit_tx_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('detected_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('sweep_preparation_tx_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('sweep_tx_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_wallets_defi_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('network', models.CharField(blank=True, choices=[('trc20', 'USDT - TRC20'), ('arbitrum', 'USDT - Arbitrum One'), ('bep20', 'USDT - BNB Smart Chain (BEP20)')], max_length=20, null=True)),
                ('target_wallet', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, db_index=True, help_text='Хеш транзакции в блокчейне', max_length=256, null=True, unique=True)),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке, если вывод не удался', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='defi_bot.investmentaccount')),
            ],
            options={
                'verbose_name': 'Запрос на вывод',
                'verbose_name_plural': 'Запросы на вывод',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('success', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_payouts_defi_bot', to='defi_bot.investmentaccount')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
