from django.urls import path
from .views import (
    InvestmentStatusView,
    CreateDepositView,
    ActivateInvestmentView,
    PayoutHistoryView,
    InvestmentConfigView,
    PayoutUpdateView,
    WithdrawalRequestUpdateView,
    WithdrawDepositView,
    InvestmentDepositHistoryView,
    SuccessfulDailyPayoutHistoryView,
    WithdrawalHistoryView,
    RequestTemporaryWalletView,
    NotifyDepositView,
    NotifySweepStatusView,
    UserTemporaryWalletsListView,
    PendingDepositWalletsListView,
    TemporaryWalletEncryptedKeyView,
    PayoutStatusView,
    WithdrawalRequestStatusView
)

urlpatterns = [
    path('status/', InvestmentStatusView.as_view(), name='spot_scalping_investment_status'),
    path('config/', InvestmentConfigView.as_view(), name='spot_scalping_investment_config'),
    path('deposit/', CreateDepositView.as_view(), name='spot_scalping_create_deposit'),
    path('deposits/history/', InvestmentDepositHistoryView.as_view(), name='spot_scalping_deposit_history'),
    path('activate/', ActivateInvestmentView.as_view(), name='spot_scalping_activate_investment'),
    path('payouts/history/', PayoutHistoryView.as_view(), name='spot_scalping_payout_history'),
    path('payouts/history/successful/', SuccessfulDailyPayoutHistoryView.as_view(), name='spot_scalping_successful_payout_history'),
    path('payouts/<int:pk>/update/', PayoutUpdateView.as_view(), name='spot_scalping_payout_update_worker'),
    path('withdraw/deposit/', WithdrawDepositView.as_view(), name='spot_scalping_create_withdrawal'),
    path('withdrawals/history/', WithdrawalHistoryView.as_view(), name='spot_scalping_withdrawal_history'),
    path('withdrawal-requests/<uuid:pk>/update_status/', WithdrawalRequestUpdateView.as_view(), name='spot_scalping_withdrawal_update_status_worker'),
    path('withdrawals/', WithdrawalHistoryView.as_view(), name='spot_scalping_withdrawal_request_list'),
    path('temp-wallets/request/', RequestTemporaryWalletView.as_view(), name='spot_scalping_request_temporary_wallet'),
    path('temp-wallets/list/', UserTemporaryWalletsListView.as_view(), name='spot_scalping_list_user_temporary_wallets'),
    path('temp-wallets/notify-deposit/', NotifyDepositView.as_view(), name='spot_scalping_notify_deposit'),
    path('temp-wallets/notify-sweep/', NotifySweepStatusView.as_view(), name='spot_scalping_notify_sweep'),
    path('temp-wallets/pending-deposit/', PendingDepositWalletsListView.as_view(), name='spot_scalping_list_pending_deposit_wallets'),
    path('temp-wallets/<int:wallet_id>/encrypted-key/', TemporaryWalletEncryptedKeyView.as_view(), name='spot_scalping_get_temporary_wallet_encrypted_key'),
    path('payouts/<int:pk>/status/', PayoutStatusView.as_view(), name='spot_scalping_payout_status'),
    path('withdrawals/<uuid:pk>/status/', WithdrawalRequestStatusView.as_view(), name='spot_scalping_withdrawal_status'),
]
